#!/bin/bash

_kill_procs() {
  kill -TERM $chromium
  wait $chromium
  kill -TERM $xvfb
}

# Setup a trap to catch SIGTERM and relay it to child processes
trap _kill_procs SIGTERM

XVFB_WHD=${XVFB_WHD:-1280x720x16}

# Start Xvfb
Xvfb :99 -ac -screen 0 $XVFB_WHD -nolisten tcp &
xvfb=$!

export DISPLAY=:99

chromium --no-sandbox --disable-software-rasterizer --disable-dev-shm-usage --remote-debugging-port=9222 --load-extension=uBlock0.chromium --remote-debugging-address=0.0.0.0 --disable-web-security --disable-features=IsolateOrigins,site-per-process --remote-allow-origins=* --disable-gpu --use-gl=desktop $@ &
chromium=$!

wait $chromium
wait $xvfb
